import { generateKeyPairSync } from "node:crypto";
import { writeFileSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

const DEFAULT_MODEL = "anthropic/claude-sonnet-4";
const DEFAULT_SYSTEM_PROMPT = `You are a helpful AI assistant participating in the PairAI collaboration network. You work on tasks assigned to you by other agents and their users.`;

export async function runSetup(agentName: string, hubUrl: string, configPath: string): Promise<void> {
  const openrouterKey = process.env.OPENROUTER_API_KEY;
  if (!openrouterKey) {
    console.error("  Error: OPENROUTER_API_KEY environment variable is required for setup.");
    console.error("  Get your key at https://openrouter.ai/keys");
    process.exit(1);
  }

  console.log("\n  Generating RSA-4096 keypair...");
  const { publicKey, privateKey } = generateKeyPairSync("rsa", {
    modulusLength: 4096,
    publicKeyEncoding: { type: "spki", format: "pem" },
    privateKeyEncoding: { type: "pkcs8", format: "pem" },
  });

  console.log(`  Registering "${agentName}" with ${hubUrl}...`);
  const res = await fetch(`${hubUrl}/agents`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ name: agentName, publicKey }),
  });

  if (!res.ok) {
    const body = await res.json().catch(() => ({})) as { error?: string };
    console.error(`  Registration failed: ${body.error ?? res.status}`);
    process.exit(1);
  }

  const { id, apiKey } = (await res.json()) as { id: string; apiKey: string };

  const configDir = dirname(configPath);
  mkdirSync(configDir, { recursive: true });
  const keyPath = join(configDir, "bridge_private.pem");
  writeFileSync(keyPath, privateKey, { mode: 0o600 });

  // Build config as object, then serialize — avoids YAML injection via crafted values
  const esc = (s: string) => JSON.stringify(s); // JSON-safe quoting works for YAML strings
  const yaml = `# PairAI OpenRouter Bridge config
# Generated by pairai-bridge setup

hub_url: ${esc(hubUrl)}
api_key: ${esc(apiKey)}
key_file: ${esc(keyPath)}

# OpenRouter — override model with OPENROUTER_MODEL env var
openrouter_key: ${esc(openrouterKey)}
model: ${esc(DEFAULT_MODEL)}
temperature: 0.7
max_reply_tokens: 4096

# Context
max_history_tokens: 32000
system_prompt: ${esc(DEFAULT_SYSTEM_PROMPT)}

# Polling
poll_interval_ms: 5000

# Logging
log_level: "info"
`;

  writeFileSync(configPath, yaml, { mode: 0o600 });

  console.log(`
  Setup complete!

  Agent ID:     ${id}
  Config:       ${configPath}
  Private key:  ${keyPath}

  BACK UP YOUR PRIVATE KEY — if lost, you must re-register.

  Start the bridge:
    npx pairai-bridge serve --config ${configPath}

  Pair with another agent:
    npx pairai-bridge invite --config ${configPath}
`);
}
